import { useState } from 'react'
import { useAuth } from '../AuthContext'

type TopBarProps = {
  fairnessScore: number | null
  auditData: any
}

export default function TopBar({ fairnessScore, auditData }: TopBarProps) {
  const { user, signOut } = useAuth()
  const [showNotif, setShowNotif] = useState(false)
  const [showUser, setShowUser] = useState(false)

  const avatarInitial = (user?.displayName?.[0] || user?.email?.[0] || 'U').toUpperCase()
  const displayName = user?.displayName || user?.email?.split('@')[0] || 'User'
  const displayEmail = user?.email || ''

  const notifications = auditData ? [
    { msg: `Bias detected on "${auditData.protectedAttribute || 'demographic'}" attribute`, time: 'Just now', type: 'warn' },
    { msg: `Disparate Impact: ${(auditData.disparateImpact || 0).toFixed(3)} — ${(auditData.disparateImpact || 0) < 0.8 ? 'Below 4/5ths legal threshold' : 'Passes threshold'}`, time: '1m ago', type: (auditData.disparateImpact || 0) < 0.8 ? 'warn' : 'ok' },
    { msg: 'Audit complete — report ready to export', time: '2m ago', type: 'ok' },
  ] : []

  const handleExport = () => {
    if (!auditData) return
    const reportText = `
BiasLens Regulatory Audit Report
==================================
Generated: ${new Date().toLocaleString()}
Dataset: ${auditData.filename || 'Unknown'}
Records Analysed: ${auditData.rows || 'N/A'}
Protected Attribute: ${auditData.protectedAttribute || 'N/A'}
Fairness Score: ${fairnessScore ?? 'N/A'} / 100

FAIRNESS METRICS
----------------
Demographic Parity:   ${auditData.demographicParity?.toFixed(4) ?? 'N/A'}   ${(auditData.demographicParity ?? 1) < 0.1 ? '[PASS]' : '[WATCH]'}
Equal Opportunity:    ${auditData.equalOpportunity?.toFixed(4) ?? 'N/A'}   ${(auditData.equalOpportunity ?? 1) < 0.1 ? '[PASS]' : '[WATCH]'}
Equalized Odds:       ${auditData.equalizedOdds?.toFixed(4) ?? 'N/A'}
Disparate Impact:     ${auditData.disparateImpact?.toFixed(4) ?? 'N/A'}   ${(auditData.disparateImpact ?? 0) >= 0.8 ? '[PASS]' : '[FAIL — below 4/5ths rule]'}

REGULATORY COMPLIANCE
---------------------
EU AI Act (High Risk):       ${auditData.compliance?.eu_ai_act ?? 'N/A'}
NYC Local Law 144 (AEDT):    ${auditData.compliance?.nyc_law_144 ?? 'N/A'}
NIST AI Framework:           COMPLIANT
California CPRA:             PENDING

GROUP APPROVAL RATES
--------------------
${(auditData.group_data || []).map((g: any) => `${String(g.name).padEnd(20)} ${g.approvalRate?.toFixed(1)}%`).join('\n') || 'N/A'}

AI AUDIT NARRATIVE
------------------
${auditData.geminiNarrative ?? 'No narrative generated.'}

--
Report generated by BiasLens AI Fairness Auditor v2.1
    `.trim()

    const blob = new Blob([reportText], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `biaslens-audit-${new Date().toISOString().slice(0, 10)}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div style={{
      height: 56,
      backgroundColor: '#ffffff',
      borderBottom: '1px solid var(--border)',
      display: 'flex',
      alignItems: 'center',
      padding: '0 24px',
      gap: 16,
      flexShrink: 0,
      position: 'relative',
      zIndex: 100,
    }}>
      {/* Left side */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 16, flex: 1 }}>
        <span style={{ fontSize: 13, color: 'var(--text-muted)', fontWeight: 500, fontFamily: 'JetBrains Mono, monospace' }}>
          {auditData?.filename ? `📄 ${auditData.filename}` : 'BiasLens v2.1'}
        </span>
        {auditData && (
          <>
            <div style={{ width: 1, height: 18, backgroundColor: 'var(--border)' }} />
            <span style={{ fontSize: 12, color: 'var(--text-muted)' }}>
              {(auditData.rows || 0).toLocaleString()} records · {auditData.columns?.length || 0} features · <span style={{ fontWeight: 600, color: 'var(--accent-blue)' }}>{auditData.protectedAttribute || 'demographic'}</span>
            </span>
          </>
        )}
        {fairnessScore !== null && (
          <>
            <div style={{ width: 1, height: 18, backgroundColor: 'var(--border)' }} />
            <span style={{
              fontSize: 13, fontWeight: 700,
              color: fairnessScore >= 80 ? 'var(--accent-green)' : fairnessScore >= 60 ? 'var(--accent-amber)' : 'var(--accent-red)',
              display: 'flex', alignItems: 'center', gap: 6,
            }}>
              <span style={{
                width: 6, height: 6, borderRadius: '50%',
                backgroundColor: fairnessScore >= 80 ? 'var(--accent-green)' : 'var(--accent-amber)',
                display: 'inline-block'
              }} className="pulse" />
              Fairness Score: {fairnessScore}/100
            </span>
          </>
        )}
        {auditData && (
          <>
            <div style={{ width: 1, height: 18, backgroundColor: 'var(--border)' }} />
            <span style={{
              fontSize: 11, fontWeight: 600, padding: '2px 10px',
              backgroundColor: '#d1fae5', color: '#059669',
              borderRadius: 999, textTransform: 'uppercase', letterSpacing: '0.04em'
            }}>
              Active Session
            </span>
          </>
        )}
      </div>

      {/* Right side */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, position: 'relative' }}>

        {/* Bell with dropdown */}
        <div style={{ position: 'relative' }}>
          <button
            onClick={() => { setShowNotif(v => !v); setShowUser(false) }}
            style={{
              width: 36, height: 36, borderRadius: 8,
              border: `1px solid ${showNotif ? 'var(--accent-blue)' : 'var(--border)'}`,
              backgroundColor: showNotif ? 'var(--accent-blue-light)' : 'white',
              cursor: 'pointer',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              color: showNotif ? 'var(--accent-blue)' : 'var(--text-secondary)',
              position: 'relative',
            }}
          >
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"/>
              <path d="M13.73 21a2 2 0 0 1-3.46 0"/>
            </svg>
            {auditData && (
              <span style={{
                position: 'absolute', top: 6, right: 6,
                width: 7, height: 7, borderRadius: '50%',
                backgroundColor: 'var(--accent-red)', border: '1.5px solid white',
              }} />
            )}
          </button>
          {showNotif && (
            <div style={{
              position: 'absolute', top: 42, right: 0,
              width: 320, backgroundColor: 'white',
              border: '1px solid var(--border)', borderRadius: 10,
              boxShadow: '0 8px 24px rgba(0,0,0,0.1)',
              zIndex: 999,
            }}>
              <div style={{ padding: '12px 16px', borderBottom: '1px solid var(--border)', fontSize: 13, fontWeight: 700 }}>
                Notifications {auditData && <span style={{ fontSize: 11, color: 'var(--accent-red)', marginLeft: 6, fontWeight: 600 }}>{notifications.length} new</span>}
              </div>
              {notifications.length === 0 ? (
                <div style={{ padding: 16, fontSize: 12, color: 'var(--text-muted)', textAlign: 'center' }}>
                  Upload a dataset to see alerts
                </div>
              ) : (
                notifications.map((n, i) => (
                  <div key={i} style={{ padding: '12px 16px', borderBottom: '1px solid var(--border)', display: 'flex', gap: 10 }}>
                    <span style={{ fontSize: 14, marginTop: 1 }}>{n.type === 'warn' ? '⚠️' : '✅'}</span>
                    <div>
                      <div style={{ fontSize: 12, fontWeight: 500, color: 'var(--text-primary)', lineHeight: 1.5 }}>{n.msg}</div>
                      <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 2 }}>{n.time}</div>
                    </div>
                  </div>
                ))
              )}
            </div>
          )}
        </div>

        {/* User avatar with dropdown */}
        <div style={{ position: 'relative' }}>
          <button
            id="btn-user-menu"
            onClick={() => { setShowUser(v => !v); setShowNotif(false) }}
            style={{
              width: 36, height: 36, borderRadius: 8,
              background: showUser
                ? 'linear-gradient(135deg, #2d4dcc 0%, #6d28d9 100%)'
                : 'linear-gradient(135deg, #3b5bdb 0%, #7c3aed 100%)',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              color: 'white', fontSize: 13, fontWeight: 700,
              border: 'none', cursor: 'pointer',
              boxShadow: '0 2px 8px rgba(59,91,219,0.35)',
              transition: 'box-shadow 0.15s',
              overflow: 'hidden',
            }}
          >
            {user?.photoURL ? (
              <img
                src={user.photoURL}
                alt={displayName}
                style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                referrerPolicy="no-referrer"
              />
            ) : avatarInitial}
          </button>
          {showUser && (
            <div style={{
              position: 'absolute', top: 42, right: 0,
              width: 240, backgroundColor: 'white',
              border: '1px solid var(--border)', borderRadius: 12,
              boxShadow: '0 12px 32px rgba(0,0,0,0.12)',
              zIndex: 999,
              overflow: 'hidden',
            }}>
              {/* User info header */}
              <div style={{
                padding: '14px 16px',
                borderBottom: '1px solid var(--border)',
                display: 'flex', alignItems: 'center', gap: 12,
              }}>
                <div style={{
                  width: 38, height: 38, borderRadius: 8, flexShrink: 0,
                  background: 'linear-gradient(135deg, #3b5bdb 0%, #7c3aed 100%)',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  color: 'white', fontSize: 15, fontWeight: 700,
                  overflow: 'hidden',
                }}>
                  {user?.photoURL ? (
                    <img src={user.photoURL} alt={displayName}
                      style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                      referrerPolicy="no-referrer"
                    />
                  ) : avatarInitial}
                </div>
                <div style={{ minWidth: 0 }}>
                  <div style={{ fontSize: 13, fontWeight: 700, color: 'var(--text-primary)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{displayName}</div>
                  <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 2, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{displayEmail}</div>
                </div>
              </div>
              {/* Sign out */}
              <button
                id="btn-sign-out"
                onClick={() => { setShowUser(false); signOut() }}
                style={{
                  width: '100%', padding: '11px 16px', border: 'none',
                  backgroundColor: 'transparent', textAlign: 'left',
                  fontSize: 13, cursor: 'pointer',
                  color: 'var(--accent-red)',
                  display: 'flex', alignItems: 'center', gap: 8,
                  fontFamily: 'Inter, sans-serif', fontWeight: 500,
                  transition: 'background 0.12s',
                }}
                onMouseEnter={e => (e.currentTarget.style.backgroundColor = '#fef2f2')}
                onMouseLeave={e => (e.currentTarget.style.backgroundColor = 'transparent')}
              >
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/>
                  <polyline points="16 17 21 12 16 7"/>
                  <line x1="21" y1="12" x2="9" y2="12"/>
                </svg>
                Sign Out
              </button>
            </div>
          )}
        </div>

        {/* Export Report */}
        <button
          onClick={handleExport}
          disabled={!auditData}
          style={{
            display: 'flex', alignItems: 'center', gap: 6,
            padding: '8px 16px', borderRadius: 8,
            backgroundColor: auditData ? 'var(--bg-sidebar)' : 'var(--border)',
            color: auditData ? 'white' : 'var(--text-muted)',
            border: 'none', fontSize: 13, fontWeight: 600,
            cursor: auditData ? 'pointer' : 'default',
            transition: 'background 0.15s',
          }}
          onMouseEnter={e => { if (auditData) e.currentTarget.style.background = '#1d2432' }}
          onMouseLeave={e => { if (auditData) e.currentTarget.style.background = 'var(--bg-sidebar)' }}
        >
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
            <polyline points="7,10 12,15 17,10"/><line x1="12" y1="15" x2="12" y2="3"/>
          </svg>
          Export Report
        </button>
      </div>

      {/* Backdrop to close dropdowns */}
      {(showNotif || showUser) && (
        <div
          style={{ position: 'fixed', inset: 0, zIndex: 99 }}
          onClick={() => { setShowNotif(false); setShowUser(false) }}
        />
      )}
    </div>
  )
}
